### PR TITLE
Add correct folder structure

### PR DESCRIPTION
**Pull request by johlju**
This adds the correct folder structure for class-based resources. This will make sure the resource is found when running `Get-DscResource`.

This PR just renames the folders, and adds a main module manifest (with new unique guid) that loads (nested) all class-based resource (although there is only one today).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/jea/50)

### CODE REVIEW

**Comment by johlju** [comment]
@rpsqrd do you mind reviewing this PR. or tag the one that are able to review? Thanks

**Review by ChrisLGardner — COMMENTED** [review]
Should the JustEnoughAdministration.psm1 and psd1 under JeaEndpoint actually be named the same as that? Since they set up endpoints it would make more sense that way I think.

**Comment by johlju** [comment]
@ChrisLGardner Agree, renamed.

**Review by ChrisLGardner — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/jea/50)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
